export const details = [
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/6F17MbloTeRoXs7JI3lTHy"
        },
        "href": "https://api.spotify.com/v1/albums/6F17MbloTeRoXs7JI3lTHy",
        "id": "6F17MbloTeRoXs7JI3lTHy",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/2794cec1cb0725154988cd2dde202e278e3023de",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/bcf636076bd3923353386d4f9e5053db746de48e",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/68cb58484d9b3a629482aba538930f5d4f1f5238",
                "width": 64
            }
        ],
        "name": "Real Gone (Remastered)",
        "release_date": "2004-10-05",
        "release_date_precision": "day",
        "total_tracks": 16,
        "type": "album",
        "uri": "spotify:album:6F17MbloTeRoXs7JI3lTHy"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/5kngzyNwERbKiQDvVwsgMt"
        },
        "href": "https://api.spotify.com/v1/albums/5kngzyNwERbKiQDvVwsgMt",
        "id": "5kngzyNwERbKiQDvVwsgMt",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/acf8988b195508b68afa2f5e4be5d3ce359aece1",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/0c7aef8417440c95e8a985ec094775bfd6f7f804",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/dc3aa46625605b433063e4063424e46e8be500e8",
                "width": 64
            }
        ],
        "name": "Bad As Me (Deluxe Edition Remastered)",
        "release_date": "2011-10-25",
        "release_date_precision": "day",
        "total_tracks": 16,
        "type": "album",
        "uri": "spotify:album:5kngzyNwERbKiQDvVwsgMt"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/6GjMcck9c4i6cQo194xKl6"
        },
        "href": "https://api.spotify.com/v1/albums/6GjMcck9c4i6cQo194xKl6",
        "id": "6GjMcck9c4i6cQo194xKl6",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/d5e0b48460ded61b5337e8bcb724ec265c1da3cb",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/854b20731bc75259116f6bbc0f32442eb8dd5de5",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/5573f5b2ddaff849f2b42660a70d27827a0dce6c",
                "width": 64
            }
        ],
        "name": "Small Change (Remastered)",
        "release_date": "1976-09-21",
        "release_date_precision": "day",
        "total_tracks": 11,
        "type": "album",
        "uri": "spotify:album:6GjMcck9c4i6cQo194xKl6"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/5blxyZRgkA735vO40p56MA"
        },
        "href": "https://api.spotify.com/v1/albums/5blxyZRgkA735vO40p56MA",
        "id": "5blxyZRgkA735vO40p56MA",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/595ebd653392f0b46fab2e58e29ea418e9b9e466",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/87e341869d14101a56200caa733a611f4a2aa9d2",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/1cc6a5160abaf377e36f2f6fa5f2aca57ed15af6",
                "width": 64
            }
        ],
        "name": "Bone Machine",
        "release_date": "1992-01-01",
        "release_date_precision": "day",
        "total_tracks": 16,
        "type": "album",
        "uri": "spotify:album:5blxyZRgkA735vO40p56MA"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/51hrKjSvIX69tl1g13R0hI"
        },
        "href": "https://api.spotify.com/v1/albums/51hrKjSvIX69tl1g13R0hI",
        "id": "51hrKjSvIX69tl1g13R0hI",
        "images": [
            {
                "height": 623,
                "url": "https://i.scdn.co/image/1a61116abcad45f5a805f0cba9461f6764f57991",
                "width": 640
            },
            {
                "height": 292,
                "url": "https://i.scdn.co/image/d99f98cf61edfd670961fe61223e0352091f7324",
                "width": 300
            },
            {
                "height": 62,
                "url": "https://i.scdn.co/image/67443042dde4f75c22e2ca5438039e5187c4db80",
                "width": 64
            }
        ],
        "name": "Swordfishtrombones",
        "release_date": "1983-09-01",
        "release_date_precision": "day",
        "total_tracks": 15,
        "type": "album",
        "uri": "spotify:album:51hrKjSvIX69tl1g13R0hI"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/2zIaHUyMLCtg7pxtp1ZpO7"
        },
        "href": "https://api.spotify.com/v1/albums/2zIaHUyMLCtg7pxtp1ZpO7",
        "id": "2zIaHUyMLCtg7pxtp1ZpO7",
        "images": [
            {
                "height": 632,
                "url": "https://i.scdn.co/image/e760eff1b91d5e9b9fadfb57ae0009d6e6486aab",
                "width": 640
            },
            {
                "height": 296,
                "url": "https://i.scdn.co/image/dd9c420015585399f9bbe64ac46fd654c69fc0ca",
                "width": 300
            },
            {
                "height": 63,
                "url": "https://i.scdn.co/image/ac1bef9874421cd9f7abfd6cfd4bf03a27e15d2d",
                "width": 64
            }
        ],
        "name": "Franks Wild Years",
        "release_date": "1987-08-17",
        "release_date_precision": "day",
        "total_tracks": 17,
        "type": "album",
        "uri": "spotify:album:2zIaHUyMLCtg7pxtp1ZpO7"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/7D22RFqWGicOV7hpIiCdlq"
        },
        "href": "https://api.spotify.com/v1/albums/7D22RFqWGicOV7hpIiCdlq",
        "id": "7D22RFqWGicOV7hpIiCdlq",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/e084b5412c8cff36a48a55933e0393b7de938688",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/8789409f3e9cf05d4c4396a5471404be42bdc405",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/ba11e9a8641bfb8898970653ea7d19e5a808845e",
                "width": 64
            }
        ],
        "name": "Blood Money (Remastered)",
        "release_date": "2002-05-07",
        "release_date_precision": "day",
        "total_tracks": 13,
        "type": "album",
        "uri": "spotify:album:7D22RFqWGicOV7hpIiCdlq"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/3zeDrhkNv8872fC7CsOCpI"
        },
        "href": "https://api.spotify.com/v1/albums/3zeDrhkNv8872fC7CsOCpI",
        "id": "3zeDrhkNv8872fC7CsOCpI",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/60d411cea7bd2324541cc2a9c086ed7c7e05e713",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/29ba45008dd92bbcaee55e56aad08b0faf705d1a",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/0dc682d4ff3119921a0ee109536af5fbc04a0f29",
                "width": 64
            }
        ],
        "name": "Alice (Remastered)",
        "release_date": "2002-05-07",
        "release_date_precision": "day",
        "total_tracks": 15,
        "type": "album",
        "uri": "spotify:album:3zeDrhkNv8872fC7CsOCpI"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/7lCEnPYYkUuvnkrCbA6RCa"
        },
        "href": "https://api.spotify.com/v1/albums/7lCEnPYYkUuvnkrCbA6RCa",
        "id": "7lCEnPYYkUuvnkrCbA6RCa",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/9e6daed2ef1da1da570d2f4a6b2d51e0b6acbd55",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/4d7e948cf0ba20eac0f9dad453cf0a93f89a6100",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/dce08902ad893ba7accb4a279d3a90cb77522e6c",
                "width": 64
            }
        ],
        "name": "Heartattack And Vine (Remastered)",
        "release_date": "1980-09-09",
        "release_date_precision": "day",
        "total_tracks": 9,
        "type": "album",
        "uri": "spotify:album:7lCEnPYYkUuvnkrCbA6RCa"
    },
    {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/7x83XhcMbOTl1UdYsPTuZM"
                },
                "href": "https://api.spotify.com/v1/artists/7x83XhcMbOTl1UdYsPTuZM",
                "id": "7x83XhcMbOTl1UdYsPTuZM",
                "name": "Tom Waits",
                "type": "artist",
                "uri": "spotify:artist:7x83XhcMbOTl1UdYsPTuZM"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/2fgQN85UzwZMRIBTs06FjX"
        },
        "href": "https://api.spotify.com/v1/albums/2fgQN85UzwZMRIBTs06FjX",
        "id": "2fgQN85UzwZMRIBTs06FjX",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/85479a96072da3e3c30acd07a545422932c17bad",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/9586e292c9bef5b4dcb1a274d2b92e74c118ebdc",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/25a03bca3bedb6b2f144258d2dc3dd8d0349cf18",
                "width": 64
            }
        ],
        "name": "Blue Valentine (Remastered)",
        "release_date": "1978-09-05",
        "release_date_precision": "day",
        "total_tracks": 10,
        "type": "album",
        "uri": "spotify:album:2fgQN85UzwZMRIBTs06FjX"
    }
];
//'3pO5VjZ4wOHCMBXOvbMISG'